"""
document_agent.py — Handles generation of Word (.docx), Excel (.xlsx), and PowerPoint (.pptx) files.
"""
from __future__ import annotations

import logging
import os
from typing import Any

from graph.state import AgentState

logger = logging.getLogger(__name__)

# Try imports for document generation libraries
try:
    import docx
except ImportError:
    docx = None

try:
    import openpyxl
except ImportError:
    openpyxl = None

try:
    import pptx
    from pptx import Presentation
except ImportError:
    pptx = None


def generate_word_document(filename: str, content: dict[str, Any]) -> str:
    """Generate a .docx file using python-docx."""
    if docx is None:
        raise RuntimeError("python-docx package is not installed.")

    doc = docx.Document()
    title = content.get("title", "Document Title")
    doc.add_heading(title, level=0)

    sections = content.get("sections", [])
    if isinstance(sections, list):
        for sec in sections:
            if isinstance(sec, dict):
                h = sec.get("heading")
                p = sec.get("paragraph")
                if h:
                    doc.add_heading(str(h), level=1)
                if p:
                    doc.add_paragraph(str(p))
            elif isinstance(sec, str):
                doc.add_paragraph(sec)
    elif isinstance(content.get("body"), str):
        doc.add_paragraph(content["body"])
    else:
        doc.add_paragraph(str(content))

    out_path = os.path.abspath(filename)
    doc.save(out_path)
    return out_path


def generate_excel_document(filename: str, content: dict[str, Any]) -> str:
    """Generate an .xlsx file using openpyxl."""
    if openpyxl is None:
        raise RuntimeError("openpyxl package is not installed.")

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = content.get("sheet_title", "Sheet1")

    columns = content.get("columns", [])
    if columns and isinstance(columns, list):
        ws.append([str(c) for c in columns])

    rows = content.get("rows", [])
    if rows and isinstance(rows, list):
        for r in rows:
            if isinstance(r, list):
                ws.append(r)
            elif isinstance(r, dict):
                ws.append([r.get(c, "") for c in columns])

    out_path = os.path.abspath(filename)
    wb.save(out_path)
    return out_path


def generate_powerpoint_document(filename: str, content: dict[str, Any]) -> str:
    """Generate a .pptx file using python-pptx."""
    if pptx is None:
        raise RuntimeError("python-pptx package is not installed.")

    prs = Presentation()
    slides_data = content.get("slides", [])

    if not slides_data:
        # Default title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = content.get("title", "Presentation Title")
        subtitle.text = content.get("subtitle", "Generated by DesktopPilot AI")
    else:
        for s_info in slides_data:
            layout_idx = s_info.get("layout", 1)  # 1 is title and content
            slide_layout = prs.slide_layouts[layout_idx] if layout_idx < len(prs.slide_layouts) else prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            if slide.shapes.title and "title" in s_info:
                slide.shapes.title.text = str(s_info["title"])
            if len(slide.placeholders) > 1:
                body_content = s_info.get("body", s_info.get("content", ""))
                if isinstance(body_content, list):
                    slide.placeholders[1].text = "\n".join(str(item) for item in body_content)
                elif body_content:
                    slide.placeholders[1].text = str(body_content)

    out_path = os.path.abspath(filename)
    prs.save(out_path)
    return out_path


async def document_agent_node(state: AgentState) -> dict[str, Any]:
    """LangGraph node: executes document generation steps."""
    plan = state.get("plan") or []
    current_step_idx = state.get("current_step", 0)

    if current_step_idx >= len(plan):
        return {
            "execution_trace": [
                {
                    "agent": "document_agent",
                    "status": "skipped",
                    "message": "No document step to execute.",
                }
            ]
        }

    step = plan[current_step_idx]
    params = step.get("params", {})
    doc_type = (params.get("doc_type") or "").lower()
    filename = params.get("output_filename") or f"output_{current_step_idx+1}"
    content = params.get("content") or {}

    try:
        if doc_type in ("word", "docx") or filename.endswith(".docx"):
            if not filename.endswith(".docx"):
                filename += ".docx"
            out_file = generate_word_document(filename, content)
        elif doc_type in ("excel", "xlsx") or filename.endswith(".xlsx"):
            if not filename.endswith(".xlsx"):
                filename += ".xlsx"
            out_file = generate_excel_document(filename, content)
        elif doc_type in ("powerpoint", "pptx") or filename.endswith(".pptx"):
            if not filename.endswith(".pptx"):
                filename += ".pptx"
            out_file = generate_powerpoint_document(filename, content)
        else:
            raise ValueError(f"Unsupported or unknown doc_type: {doc_type}")

        res = {"success": True, "output_file": out_file, "message": f"Generated document: {out_file}"}
        logger.info("EXECUTION TOOL: document_agent | OUTPUT FILE: %s", out_file)
        return {
            "last_execution_result": res,
            "execution_trace": [
                {
                    "agent": "document_agent",
                    "status": "success",
                    "message": f"Document created successfully at: {out_file}",
                }
            ],
        }
    except Exception as exc:
        logger.exception("Document generation failed: %s", exc)
        res = {"success": False, "error": str(exc)}
        return {
            "last_execution_result": res,
            "error": f"Document generation error: {exc}",
            "execution_trace": [
                {
                    "agent": "document_agent",
                    "status": "error",
                    "message": f"Document creation failed: {exc}",
                }
            ],
        }
