"""
state.py — State definitions for DesktopPilot multi-agent orchestration.
Defines AgentState, Capabilities, and PlanStep data schemas used across LangGraph.
"""
from __future__ import annotations

from typing import Any, Optional, TypedDict
from pydantic import BaseModel


class Capabilities(BaseModel):
    """Execution capabilities supported by the active model backend."""
    browser_automation: bool = True
    desktop_automation: bool = True
    document_generation: bool = True
    vision_agent: bool = False

    def supports_task_type(self, task_type: str) -> bool:
        if task_type == "browser_automation":
            return self.browser_automation
        if task_type == "desktop_automation":
            return self.desktop_automation
        if task_type == "document_generation":
            return self.document_generation
        return True


class PlanStep(TypedDict, total=False):
    """Single execution step generated by the Planning Agent."""
    step_id: int
    agent: str  # "document_agent" | "browser_agent" | "desktop_agent"
    action: str
    params: dict[str, Any]


class AgentState(TypedDict, total=False):
    """Full shared state passed across LangGraph nodes."""
    messages: list[dict[str, str]]
    session_id: str
    task_id: Optional[str]
    task_status: Optional[str]
    user_input: str
    task_type: Optional[str]
    requirements_complete: bool
    clarifying_question: Optional[str]
    requirements: Optional[list[dict[str, Any]]]
    satisfied_requirements: list[str]
    unsatisfied_requirements: list[str]
    plan: Optional[list[dict[str, Any]]]
    current_plan: Optional[list[dict[str, Any]]]
    previous_plan: Optional[list[dict[str, Any]]]
    current_step: int
    last_execution_result: Optional[dict[str, Any]]
    execution_results: list[dict[str, Any]]
    artifact_paths: list[str]
    generated_outputs: Optional[list[dict[str, Any]]]
    validation_result: Optional[dict[str, Any]]
    validation_status: Optional[str]  # "passed" | "failed" | "pending"
    validation_errors: list[str]
    replan_required: bool
    replan_reason: Optional[str]
    replan_count: int
    max_replans: int
    model_backend: str  # "groq" | "ollama" | "none"
    capabilities: Optional[Capabilities]
    memory_context: Optional[str]
    final_response: Optional[str]
    error: Optional[str]
    failure_reason: Optional[str]
    failure_category: Optional[str]  # F1–F14 taxonomy
    execution_trace: list[dict[str, Any]]
    experimental_fault_injection: Optional[dict[str, Any]]
